// Enums
export const FETCH_ENUMS = 'FETCH_ENUMS';
export const SET_USTAWIENIA_JEZYKTYP = 'SET_USTAWIENIA_JEZYKTYP';
export const SET_UZYTKOWNICY_ROLA = 'SET_UZYTKOWNICY_ROLA';
export const SET_CENY_DEFINICJE_ZAOKRAGLENIESPOSOBTYP='SET_CENY_DEFINICJE_ZAOKRAGLENIESPOSOBTYP';

// Global error
export const THROW_GLOBAL_ERROR = 'THROW_GLOBAL_ERROR';
export const SET_THEME_LIGHT = 'SET_THEME_LIGHT';
export const SET_THEME_DARK = 'SET_THEME_DARK';
